-- ════════════════════════════════════════════════════════════════════
-- Nag agent · initial schema
-- 6 foundation tables: events, rules, alerts, alert_dispositions,
-- integrations, learned_patterns.
-- RLS enabled on all; v1 policy is "any authenticated user" (single-user
-- app to start). Tighten when multi-user lands.
-- ════════════════════════════════════════════════════════════════════

-- ─── helper: bump updated_at ────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke execute on function public.set_updated_at() from public, anon, authenticated;

-- ─── events: unified stream from all sources ────────────────────────
create table public.events (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('gmail', 'clickup', 'gcal')),
  external_id text not null,
  external_url text,
  event_type text not null,
  subject text,
  body_excerpt text,
  sender text,
  participants text[],
  occurred_at timestamptz not null,
  due_at timestamptz,
  status text,
  raw_metadata jsonb,
  ingested_at timestamptz not null default now(),
  unique (source, external_id)
);

create index events_occurred_at_idx on public.events (occurred_at desc);
create index events_due_at_idx on public.events (due_at) where due_at is not null;
create index events_source_idx on public.events (source);

alter table public.events enable row level security;
create policy events_authenticated_all on public.events
  for all to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- ─── rules: declarative conditions + actions ────────────────────────
create table public.rules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  enabled boolean not null default true,
  conditions jsonb not null,
  actions jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger rules_set_updated_at
  before update on public.rules
  for each row execute function public.set_updated_at();

alter table public.rules enable row level security;
create policy rules_authenticated_all on public.rules
  for all to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- ─── alerts: generated by rule engine, consumed by Slack + dashboard ─
create table public.alerts (
  id uuid primary key default gen_random_uuid(),
  rule_id uuid references public.rules(id) on delete set null,
  event_id uuid references public.events(id) on delete set null,
  severity text not null check (severity in ('info', 'warn', 'critical')),
  title text not null,
  body text,
  context_links jsonb,
  status text not null default 'open' check (status in ('open', 'acknowledged', 'snoozed', 'dismissed', 'done')),
  snooze_until timestamptz,
  created_at timestamptz not null default now(),
  last_notified_at timestamptz,
  closed_at timestamptz
);

create index alerts_status_open_idx on public.alerts (status) where status = 'open';
create index alerts_snooze_idx on public.alerts (snooze_until) where status = 'snoozed';
create index alerts_rule_id_idx on public.alerts (rule_id);
create index alerts_event_id_idx on public.alerts (event_id);

alter table public.alerts enable row level security;
create policy alerts_authenticated_all on public.alerts
  for all to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- ─── alert_dispositions: user feedback, drives learning loop ────────
create table public.alert_dispositions (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid not null references public.alerts(id) on delete cascade,
  action text not null check (action in ('acknowledged', 'snoozed', 'dismissed', 'marked_done', 'false_positive')),
  snooze_duration_hours int,
  user_note text,
  created_at timestamptz not null default now()
);

create index alert_dispositions_alert_id_idx on public.alert_dispositions (alert_id);

alter table public.alert_dispositions enable row level security;
create policy alert_dispositions_authenticated_all on public.alert_dispositions
  for all to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- ─── integrations: OAuth refresh tokens + sync cursors ──────────────
create table public.integrations (
  id uuid primary key default gen_random_uuid(),
  service text not null unique check (service in ('gmail', 'clickup', 'gcal', 'slack')),
  encrypted_credentials text,
  last_sync_at timestamptz,
  sync_cursor text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger integrations_set_updated_at
  before update on public.integrations
  for each row execute function public.set_updated_at();

alter table public.integrations enable row level security;
create policy integrations_authenticated_all on public.integrations
  for all to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- ─── learned_patterns: aggregated signals for rule suggestions ──────
create table public.learned_patterns (
  id uuid primary key default gen_random_uuid(),
  pattern_type text not null,
  details jsonb,
  suggested_action text,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  surfaced_at timestamptz not null default now()
);

create index learned_patterns_status_pending_idx on public.learned_patterns (status) where status = 'pending';

alter table public.learned_patterns enable row level security;
create policy learned_patterns_authenticated_all on public.learned_patterns
  for all to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
